"""Initial migration.

Revision ID: b8edd61c8626
Revises: 
Create Date: 2020-11-03 13:11:33.621308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8edd61c8626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('data_de_cadastro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('checks',
    sa.Column('id_pont', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_responsavel', sa.String(length=255), nullable=True),
    sa.Column('tipo_da_batida', sa.String(length=30), nullable=True),
    sa.Column('data_hora_batida', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_pont')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checks')
    op.drop_table('users')
    # ### end Alembic commands ###
